name: Build PHP
on:
  push:
    # By specifying branches explicitly, we avoid this workflow from
    # running on tag push. We have a dedicated workflow to be ran when
    # a tag is pushed.
    branches:
      - main
  pull_request:
jobs:
  build-php:
    strategy:
      fail-fast: false
      matrix:
        flavor: ["", "-wasmedge", "-slim"]
        version: [8.1.11, 8.2.0, 8.2.6]
        exclude:
          - flavor: "-wasmedge"
            version: 8.1.11
          - flavor: "-slim"
            version: 8.1.11
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build PHP
        run: make php/v${{ matrix.version }}${{ matrix.flavor }}
      - name: Upload php-${{ matrix.version }} assets
        uses: actions/upload-artifact@v4
        with:
          name: php-${{ matrix.version }}.zip
          path: |
            build-output/*.gz
            build-output/*.wasm
            build-output/*.txt
          if-no-files-found: error
