name: Build Ruby
on:
  push:
    # By specifying branches explicitly, we avoid this workflow from
    # running on tag push. We have a dedicated workflow to be ran when
    # a tag is pushed.
    branches:
      - main
  pull_request:
jobs:
  build-ruby:
    strategy:
      fail-fast: false
      matrix:
        flavor: ["", "-slim"]
        version: ["3.2.0", "3.2.2"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Ruby
        run: make ruby/v${{ matrix.version }}${{ matrix.flavor }}
      - name: Upload ruby-${{ matrix.version }} assets
        uses: actions/upload-artifact@v4
        with:
          name: ruby-${{ matrix.version }}.zip
          path: |
            build-output/*.gz
            build-output/*.wasm
            build-output/*.txt
          if-no-files-found: error
